import { Competition, User, Registration, CategoryItem } from '../types';

export const INITIAL_CATEGORIES: CategoryItem[] = [
  {
    id: 'cat-1',
    slug: 'ELECTRONICS',
    name: 'Electronics',
    description: 'Hardware, circuit design, FPGA, embedded systems, microcontrollers, and PCB prototyping.',
    icon: 'memory',
    orderNum: 1,
    createdAt: new Date('2026-01-01T00:00:00Z').toISOString(),
  },
  {
    id: 'cat-2',
    slug: 'ROBOTICS',
    name: 'Robotics',
    description: 'Autonomous rovers, combat sumo-bots, line followers, drone navigation, and mechatronic systems.',
    icon: 'smart_toy',
    orderNum: 2,
    createdAt: new Date('2026-01-01T00:00:00Z').toISOString(),
  },
  {
    id: 'cat-3',
    slug: 'PROGRAMMING',
    name: 'Programming',
    description: 'Algorithmic speed coding, software development sprints, web engineering, and competitive hacking.',
    icon: 'terminal',
    orderNum: 3,
    createdAt: new Date('2026-01-01T00:00:00Z').toISOString(),
  },
  {
    id: 'cat-4',
    slug: 'PROJECTS',
    name: 'Projects',
    description: 'Final Year Projects (FYP), research showcases, industrial prototypes, and commercial inventions.',
    icon: 'devices',
    orderNum: 4,
    createdAt: new Date('2026-01-01T00:00:00Z').toISOString(),
  },
  {
    id: 'cat-5',
    slug: 'ESPORTS',
    name: 'Esports',
    description: 'Competitive tactical gaming tournaments, multiplayer team matches, and esports arena showdowns.',
    icon: 'sports_esports',
    orderNum: 5,
    createdAt: new Date('2026-01-01T00:00:00Z').toISOString(),
  }
];

export const INITIAL_USERS: User[] = [
  {
    id: 'user-admin-1',
    name: 'Engr. Dr. Hashir Kidwai',
    email: 'admin@neduet.edu.pk',
    password: 'admin123',
    role: 'ADMIN',
    university: 'NED University of Engineering & Technology',
    studentId: 'FAC-EE-001',
    department: 'Department of Electronic Engineering',
    phoneNumber: '+92 21 99261261',
    createdAt: new Date('2026-01-10T10:00:00Z').toISOString(),
  },
  {
    id: 'user-student-1',
    name: 'Muhammad Ali',
    email: 'm.ali@cloud.neduet.edu.pk',
    password: 'user123',
    role: 'USER',
    university: 'NED University of Eng. & Tech.',
    studentId: 'ES-042/2022',
    department: 'Electronic Engineering',
    phoneNumber: '+92 300 1234567',
    createdAt: new Date('2026-02-15T14:30:00Z').toISOString(),
  },
  {
    id: 'user-student-2',
    name: 'Ayesha Siddiqui',
    email: 'ayesha.s@nust.edu.pk',
    password: 'user123',
    role: 'USER',
    university: 'National University of Sciences & Technology',
    studentId: 'BESE-21-089',
    department: 'Software Engineering',
    phoneNumber: '+92 312 9876543',
    createdAt: new Date('2026-02-18T09:15:00Z').toISOString(),
  }
];

export const INITIAL_COMPETITIONS: Competition[] = [
  {
    id: 'comp-01',
    slug: 'project-poster',
    orderNum: 1,
    title: 'Project & Poster Exhibition',
    category: 'PROJECTS',
    description: 'Showcase capstone hardware and research prototypes evaluated by senior faculty and industry engineering panels.',
    format: 'TEAM',
    minMembers: 2,
    maxMembers: 4,
    soloFee: 0,
    teamFee: 2500,
    keyDeliverables: 'Working hardware prototype or simulation testbed alongside standard A1 research poster presentation.',
    specsSummary: '1 to 4 Members | Display bench & AC power outlet provided',
    isActive: true,
  },
  {
    id: 'comp-02',
    slug: 'circuit-designing',
    orderNum: 2,
    title: 'Circuit Designing',
    category: 'ELECTRONICS',
    description: 'Analyze circuit schematics, calculate operational bias points, and assemble discrete prototypes on breadboards under timed constraints.',
    format: 'BOTH',
    minMembers: 1,
    maxMembers: 2,
    soloFee: 1000,
    teamFee: 1800,
    keyDeliverables: 'Components and breadboard provided on-site. Graded on circuit accuracy, stability, and speed of assembly.',
    specsSummary: 'Individual or Duo | Analog & Digital components with lab bench equipment',
    isActive: true,
  },
  {
    id: 'comp-03',
    slug: 'circuit-simulation',
    orderNum: 3,
    title: 'Circuit Simulation',
    category: 'ELECTRONICS',
    description: 'Model transient, frequency response, and stability characteristics for complex analog and digital circuits using SPICE suites.',
    format: 'BOTH',
    minMembers: 1,
    maxMembers: 2,
    soloFee: 1000,
    teamFee: 1800,
    keyDeliverables: 'Conducted in Proteus / Multisim / LTspice environments. Evaluated on convergence, parameter sweep depth, and output accuracy.',
    specsSummary: 'Individual or Duo | EDA software bench setup provided',
    isActive: true,
  },
  {
    id: 'comp-04',
    slug: 'speedy-soldering',
    orderNum: 4,
    title: 'Speedy Soldering',
    category: 'ELECTRONICS',
    description: 'Precision through-hole and SMD soldering tested for IPC joint reliability, alignment accuracy, and thermal control under clock pressure.',
    format: 'SOLO',
    minMembers: 1,
    maxMembers: 1,
    soloFee: 1000,
    teamFee: 0,
    keyDeliverables: 'Kit provided at station. Assessed on joint wetting, no cold bridges, pad integrity, and circuit continuity.',
    specsSummary: 'Solo Track | Soldering station, ESD safe tools & PCB kits provided',
    isActive: true,
  },
  {
    id: 'comp-05',
    slug: 'brainvolt',
    orderNum: 5,
    title: 'Brainvolt (Tech Quiz)',
    category: 'ELECTRONICS',
    description: 'Rapid-fire technical buzzer challenge testing foundational mastery across semiconductor physics, circuit theory, and logic design.',
    format: 'TEAM',
    minMembers: 2,
    maxMembers: 2,
    soloFee: 0,
    teamFee: 1500,
    keyDeliverables: '3 knockout rounds: Written Qualifier, Rapid Conceptual Fire, and Final Hardware Buzzer round.',
    specsSummary: 'Teams of 2 Members | Hardware and electronics buzzer quiz format',
    isActive: true,
  },
  {
    id: 'comp-06',
    slug: 'speed-programming',
    orderNum: 6,
    title: 'Speed Programming',
    category: 'PROGRAMMING',
    description: 'Solve complex algorithmic challenges, data structure problems, and optimizations under stringent time and memory constraints.',
    format: 'BOTH',
    minMembers: 1,
    maxMembers: 2,
    soloFee: 1000,
    teamFee: 1800,
    keyDeliverables: 'Supported languages: C++, Python, Java. Automated testbench evaluation with instant leaderboard ranking.',
    specsSummary: 'Solo Track | Standard algorithmic workstation setup',
    isActive: true,
  },
  {
    id: 'comp-07',
    slug: 'hackathon',
    orderNum: 7,
    title: 'Hackathon',
    category: 'PROGRAMMING',
    description: 'An intensive prototyping sprint engineering functional software and embedded firmware solutions tailored to concrete industry prompts.',
    format: 'TEAM',
    minMembers: 2,
    maxMembers: 4,
    soloFee: 0,
    teamFee: 3000,
    keyDeliverables: '24-hour sprint. Prompt announced at opening ceremony. Requires live product demo, public repository, and architecture pitch.',
    specsSummary: 'Teams of 3 to 4 | 24-hour embedded systems hardware sprint',
    isActive: true,
  },
  {
    id: 'comp-08',
    slug: 'line-following-robot',
    orderNum: 8,
    title: 'Line Following Robot',
    category: 'ROBOTICS',
    description: 'Autonomous navigation through high-speed curves, line inversions, and grid intersections using tuned PID loops and IR sensor arrays.',
    format: 'TEAM',
    minMembers: 2,
    maxMembers: 4,
    soloFee: 0,
    teamFee: 2500,
    keyDeliverables: 'Dimensions max 25cm x 25cm. Fully autonomous; manual restart penalties apply. Official track specs published in guide.',
    specsSummary: 'Teams of up to 4 | Standard arena test track dimensions applied',
    isActive: true,
  },
  {
    id: 'comp-09',
    slug: 'robo-soccer',
    orderNum: 9,
    title: 'Robo Soccer',
    category: 'ROBOTICS',
    description: 'Radio-controlled tactical soccer match testing bot drivetrain agility, mechanical defense shields, and responsive ball control.',
    format: 'TEAM',
    minMembers: 2,
    maxMembers: 4,
    soloFee: 0,
    teamFee: 2500,
    keyDeliverables: 'Max bot weight 5kg, voltage limit 12V DC. 1v1 match play in 5-minute halves with standardized tennis ball.',
    specsSummary: 'Teams of up to 4 | Wireless RF/Bluetooth controller specs apply',
    isActive: true,
  },
  {
    id: 'comp-10',
    slug: 'robo-race',
    orderNum: 10,
    title: 'Robo Race',
    category: 'ROBOTICS',
    description: 'High-octane obstacle circuit race requiring fast torque regulation across ramps, gravel bridges, and sharp mechanical chicanes.',
    format: 'TEAM',
    minMembers: 2,
    maxMembers: 4,
    soloFee: 0,
    teamFee: 2500,
    keyDeliverables: 'Wireless radio or bluetooth control. 2 attempts allowed; fastest clean lap without course skips decides final ranking.',
    specsSummary: 'Teams of up to 4 | High-traction speed track arena',
    isActive: true,
  },
  {
    id: 'comp-11',
    slug: 'gaming',
    orderNum: 11,
    title: 'Gaming Competitions',
    category: 'ESPORTS',
    description: 'Inter-university tactical esports tournament staged in the department computing facilities. Games: To Be Announced.',
    format: 'BOTH',
    minMembers: 1,
    maxMembers: 4,
    soloFee: 800,
    teamFee: 2400,
    keyDeliverables: 'Official esports rulebooks apply. Bring your own peripherals (keyboards/mice/headsets). Specific titles announced 1 week prior.',
    specsSummary: 'Solo & Team (1–4 Members) | LAN arena setup with official tournament rules',
    isActive: true,
  }
];

export const INITIAL_REGISTRATIONS: Registration[] = [
  {
    id: 'reg-001',
    registrationId: 'SPEC26-NED-88421',
    userId: 'user-student-1',
    competitionId: 'comp-01',
    competitionTitle: 'Project & Poster Exhibition',
    competitionCategory: 'PROJECTS',
    participationModel: 'TEAM',
    teamName: 'NED Apex Avionics',
    fullName: 'Muhammad Ali',
    studentId: 'ES-042/2022',
    universityName: 'NED University of Eng. & Tech.',
    department: 'Electronic Engineering',
    academicYear: 'final-year',
    phoneNumber: '+92 300 1234567',
    emailAddress: 'm.ali@cloud.neduet.edu.pk',
    paymentChannel: 'raast',
    transactionId: 'RAAST-TRX-982410842',
    receiptUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=600&auto=format&fit=crop&q=80',
    receiptFileName: 'raast_receipt_88421.png',
    status: 'VERIFIED',
    calculatedFee: 2500,
    notes: 'Payment verified by Electronic Dept desk.',
    createdAt: new Date('2026-03-01T11:20:00Z').toISOString(),
    teamMembers: [
      { id: 'tm-1', registrationId: 'reg-001', memberIndex: 2, name: 'Bilal Ahmed', studentId: 'ES-049/2022', email: 'bilal.a@cloud.neduet.edu.pk' },
      { id: 'tm-2', registrationId: 'reg-001', memberIndex: 3, name: 'Hamza Khan', studentId: 'ES-061/2022', email: 'hamza.k@cloud.neduet.edu.pk' }
    ]
  },
  {
    id: 'reg-002',
    registrationId: 'SPEC26-NED-90214',
    userId: 'user-student-2',
    competitionId: 'comp-07',
    competitionTitle: 'Hackathon',
    competitionCategory: 'PROGRAMMING',
    participationModel: 'TEAM',
    teamName: 'NUST ByteCraft',
    fullName: 'Ayesha Siddiqui',
    studentId: 'BESE-21-089',
    universityName: 'National University of Sciences & Technology',
    department: 'Software Engineering',
    academicYear: '3rd-year',
    phoneNumber: '+92 312 9876543',
    emailAddress: 'ayesha.s@nust.edu.pk',
    paymentChannel: 'nayapay-sadapay',
    transactionId: 'SADA-881294021',
    receiptUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=600&auto=format&fit=crop&q=80',
    receiptFileName: 'sadapay_proof_90214.jpg',
    status: 'PENDING',
    calculatedFee: 3000,
    notes: 'Awaiting desk transaction reconciliation.',
    createdAt: new Date('2026-03-12T16:45:00Z').toISOString(),
    teamMembers: [
      { id: 'tm-3', registrationId: 'reg-002', memberIndex: 2, name: 'Zubair Tariq', studentId: 'BESE-21-102', email: 'zubair.t@nust.edu.pk' },
      { id: 'tm-4', registrationId: 'reg-002', memberIndex: 3, name: 'Mariam Faiz', studentId: 'BESE-21-044', email: 'mariam.f@nust.edu.pk' },
      { id: 'tm-5', registrationId: 'reg-002', memberIndex: 4, name: 'Usman Farooq', studentId: 'BESE-21-118', email: 'usman.f@nust.edu.pk' }
    ]
  },
  {
    id: 'reg-003',
    registrationId: 'SPEC26-NED-71032',
    userId: 'user-student-1',
    competitionId: 'comp-04',
    competitionTitle: 'Speedy Soldering',
    competitionCategory: 'ELECTRONICS',
    participationModel: 'SOLO',
    fullName: 'Muhammad Ali',
    studentId: 'ES-042/2022',
    universityName: 'NED University of Eng. & Tech.',
    department: 'Electronic Engineering',
    academicYear: 'final-year',
    phoneNumber: '+92 300 1234567',
    emailAddress: 'm.ali@cloud.neduet.edu.pk',
    paymentChannel: 'easypaisa',
    transactionId: 'EP-44820199',
    receiptUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=600&auto=format&fit=crop&q=80',
    receiptFileName: 'easypaisa_receipt_71032.png',
    status: 'VERIFIED',
    calculatedFee: 1000,
    notes: 'Desk pass dispatched.',
    createdAt: new Date('2026-03-15T08:10:00Z').toISOString(),
    teamMembers: []
  }
];
